apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::185471904598:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-R6Z8JZWA8CU9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::185471904598:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-03T15:57:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1287"
  uid: e889b845-2a8a-44a6-942b-c1f3d4125bda
